services:
  alice:
    build: .
    ports:
      - "127.0.0.1:5001:5001"
    environment:
      - DOCKER_CONTAINER=1
      - PYTHONUNBUFFERED=1
      - ROLE=alice
    command: python src/alice/app.py
    networks:
      - crypto-net

  bob:
    build: .
    ports:
      - "127.0.0.1:5002:5002"
    environment:
      - DOCKER_CONTAINER=1
      - PYTHONUNBUFFERED=1
      - ROLE=bob
    command: python src/bob/app.py
    networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge